config/routes.rb
Rails.application.routes.draw do
  get 'groups/index'
  get 'groups/new'
  get 'groups/edit'
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/home'

  root 'visitors#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :events
  resources :users
  resources :groups
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  attr_accessor :date_range

  def all_day_event?
    self.start == self.start.midnight && self.end == self.end.midnight ? true : false
  end
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :users
    has_one :event
    validates :name, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    validates :name, presence: true, length: { maximum:50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum:6 }

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine::cost
        BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	include SessionsHelper
	
	private

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Пожалуйста, залогиньтесь."
      redirect_to login_url
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.where(start: params[:start]..params[:end])
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
  end

  def update
    @event.update(event_params)
  end

  def destroy
    @event.destroy
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :date_range, :start, :end, :color, :for_group)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.paginate(page: params[:page])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:info] = "Группа создана."
      redirect_to groups_url
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      flash[:success] = "Группа обновлена"
      redirect_to groups_url
    else
      render 'edit'
    end
  end

  def destroy
    Group.find(params[:id]).destroy
    flash[:success] = "Пользователь удален"
    redirect_to groups_url
  end

  private

  def group_params
    params.require(:group).permit(:name, :study_programm)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or root_url
    else
      flash.now[:danger] = 'Неверный email и/или пароль'
      render 'new'
    end
  end
    
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:info] = "Аккаунт создан. Теперь вы можете войти."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Профиль обновлен"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Пользователь удален"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end
  
  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
  end
	
  def admin_user
      redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id]=user.id
  end
      
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id]
    cookies.permanent[:remember_token]=user.remember_token
  end
      
  def current_user?(user)
    user == current_user
  end
      
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
      
  def logged_in?
    !current_user.nil?
  end
      
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
      
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
      
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end
      
  def store_location
    session[:forwarding_url]=request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/events/_edit.html.erb
<div class="modal fade" id="edit_event">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Отредактировать событие</h4>
      </div>
      <div class="modal-body">
        <%= render 'form', event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for @event, remote: true do |f| %>
  <div class="form-inputs">
    <%= f.label 'Название' %> <%= f.input :title %>
    <%= f.label 'Дата и время'%> <%= f.input :date_range, input_html: { class: "form-control input-sm date-range-picker" } %>
    <%= f.input_field :start, as: :hidden, value: Date.today, class: 'form-control input-sm start_hidden' %>
    <%= f.input_field :end, as: :hidden, value: Date.today, class: 'form-control input-sm end_hidden' %>
    <%= f.label 'Цвет' %> <%= f.input :color, as: :select, collection: [['Черный','black'], ['Зеленый','green'], ['Красный','red']] %>
    <%= f.label 'Для группы' %> <%= f.input :for_group %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= link_to 'Delete', 
                event, 
                method: :delete, 
                class: 'btn btn-danger', 
                data: { confirm: 'Вы уверены?' }, 
                remote: true unless @event.new_record? %>
  </div>
<% end %>

app/views/events/_new.html.erb
<div class="modal fade" id="new_event">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Создать событие</h4>
      </div>
      <div class="modal-body">
        <%= render 'form', event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/events/create.js.erb
$('.calendar').fullCalendar(
  'renderEvent', 
  $.parseJSON("<%=j render(@event, format: :json).html_safe %>"),
  true
);
$('.modal').modal('hide');

app/views/events/destroy.js.erb
$('.calendar').fullCalendar('removeEvents', [<%= @event.id %>])
$('.modal').modal('hide');

app/views/events/edit.js.erb
<% if current_user.admin? %>
$('#remote_container').html('<%= j render "edit" %>');
$('#edit_event').modal('show');
<% end %>

app/views/events/new.js.erb
<% if current_user.admin? %>
$('#remote_container').html('<%= j render "new" %>');
$('#new_event').modal('show');
<% end %>

app/views/events/update.js.erb
$('.calendar').fullCalendar('removeEvents', [<%= @event.id %>]);
$('.calendar').fullCalendar(
  'renderEvent', 
  $.parseJSON("<%=j render(@event, format: :json).html_safe %>"), 
  true
);
$('.modal').modal('hide');

app/views/groups/_group.html.erb
<li>
  <% if current_user.admin? %>
    <%= group.name %> | Учебная программа - <%= group.study_programm %>
    || <%= link_to "изменить", edit_group_path(group) %>
    | <%= link_to "удалить", group, method: :delete,
                                  data: { confirm: "Вы уверены?" } %>
  <% else %>
    <%= group.name %>
  <% end %>
</li>

app/views/groups/edit.html.erb
<h1>Изменение группы</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@group) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :study_programm %>
    <%= f.text_field :study_programm, class: 'form-control' %>

    <%= f.submit "Изменить группу", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<h1>Все группы</h1>
<%= link_to '<button type="button">Новая группа</button>'.html_safe, new_group_path %>
<%= will_paginate @groups %>

<ul class="groups">
  <%= render @groups %>
</ul>

<%= will_paginate @groups %>

app/views/groups/new.html.erb
<h1>Создание группы</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@group) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :study_programm %>
    <%= f.text_field :study_programm, class: 'form-control' %>

    <%= f.submit "Создать группу", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Ruby on Rails', pages_home_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to "Календарь консультаций", root_path %></li>
<li><%= link_to "О сайте", pages_about_path %></li>
<li><%= link_to "Связь с нами", pages_contact_path %></li>
<% if logged_in? %>
    <li><%= link_to "Пользователи", users_path %></li>
    <li><%= link_to "Группы", groups_path %></li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Аккаунт <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><%= link_to "Профиль", current_user %></li>
            <li><%= link_to "Настройки", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Выйти", logout_path, method: :delete %></li>
        </ul>
<% else %>
    <li><%= link_to "Войти", login_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RoR Diploma project" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "RoR Diploma project" %>">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class='container'>
        <%= render 'layouts/messages' %>
        <%= yield %>
        <div id='remote_container'></div>
      </div>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<div class="center jumbotron">
    <h1>Gotta go fast</h1>

    <h2>
      Так много осталось сделать... И так мало времени...
    </h2>

</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<%#= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "просмотреть мой профиль", current_user %></span>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) && !user.admin? %>
    | <%= link_to "удалить", user, method: :delete,
                                  data: { confirm: "Вы уверены?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Изменение данных</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label 'Пароль' %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label 'Подтверждение пароля' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.label 'Администратор (ТОЛЬКО ДЛЯ ДЕМОНСТРАЦИИ!)' %>
    <%= f.check_box :admin, class: 'form-control' %>

    <%= f.submit "Изменить данные аккаунта", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Все пользователи</h1>

<%= will_paginate @users %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate @users %>

app/views/users/new.html.erb
<h1>Регистрация</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label 'Имя' %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label 'Пароль' %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label 'Подтверждение пароля' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit "Создать аккаунт", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
	<section class="user_info">
	  <h1>
		<%= @user.name %>
	  </h1>
      <div>Группа - <%= @user.group_id %> </div> 
	</section>
  </aside>
</div>

app/views/visitors/index.html.erb
<div class="calendar"></div>